# Generated by Django 3.1.7 on 2025-04-30 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textanalyzer', '0002_auto_20210323_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
